base:
  random_state: 42

data_ingestion:
  input_path: data/indian_restaurant_waste_dataset.csv
  output_dir: data/processed
  test_size: 0.2

data_processing:
  input_train_path: data/processed/train.csv
  input_test_path: data/processed/test.csv
  output_train_path: data/processed/train_preprocessed.csv
  output_test_path: data/processed/test_preprocessed.csv

feature_eng:
  input_train_path: data/processed/train_preprocessed.csv
  input_test_path: data/processed/test_preprocessed.csv
  output_train_path: data/processed/train_fe.csv
  output_test_path: data/processed/test_fe.csv

model_train:
  input_train_path: data/processed/train_fe.csv
  models_output_dir: models/
  random_state: 42

  models:
    random_forest:
      model_path: models/rf_food_waste_model.pkl
      n_estimators: 200
      max_depth: 8
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42

    xgboost:
      model_path: models/xgb_food_waste_model.pkl
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42

    linear_regression:
      model_path: models/lr_food_waste_model.pkl
      fit_intercept: True
      normalize: False

model_eval:
  input_test_path: data/processed/test_fe.csv
  models_dir: models/
  metrics_txt: metrics/metrics.txt
  metrics_json: metrics/metrics.json
  comparison_plot: metrics/model_comparison.png
