data_ingestion:
  input_path: "data/raw/indian_restaurant_waste_dataset.csv"
  output_path: "data/raw/raw_data.csv"

data_preprocessing:
  input_path: "data/raw/raw_data.csv"
  output_path: "data/processed/processed_data.csv"

feature_engineering:
  input_path: "data/processed/processed_data.csv"
  output_path: "data/processed/feature_data.csv"

model_training:
  input_path: "data/processed/feature_data.csv"
  model_output: "models/xgb_food_waste_model.pkl"
  test_size: 0.2
  random_state: 42
  n_estimators: 300
  learning_rate: 0.05
  max_depth: 6

model_evaluation:
  model_path: "models/xgb_food_waste_model.pkl"
  data_path: "data/processed/feature_data.csv"
  metrics_output: "metrics.txt"
