data_ingestion:
  input_path: "data/indian_restaurant_waste_dataset.csv"
  output_path: "data/raw_data.csv"

data_preprocessing:
  input_path: "data/raw_data.csv"
  output_path: "data/processed/processed_data.csv"

feature_engineering:
  input_path: "data/processed/processed_data.csv"
  output_path: "data/processed/feature_data.csv"

model_training:
  input_path: "data/processed/feature_data.csv"
  models_output_dir: "models/"
  test_size: 0.2
  random_state: 42

  # Model configurations
  models:
    random_forest:
      model_path: "models/rf_food_waste_model.pkl"
      n_estimators: 200
      max_depth: 8
      min_samples_split: 5
      min_samples_leaf: 2

    xgboost:
      model_path: "models/xgb_food_waste_model.pkl"
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8

    linear_regression:
      model_path: "models/lr_food_waste_model.pkl"
      normalize: True

model_evaluation:
  data_path: "data/processed/feature_data.csv"
  metrics_output: "metrics/metrics.txt"
  comparison_plot: "metrics/model_comparison.png"
