base:
  random_state: 42

data_ingestion:
  input_path: data/indian_restaurant_waste_dataset.csv
  output_dir: data/processed
  test_size: 0.2

data_preprocessing:
  input_dir: data/processed
  output_dir: data/preprocessed

feature_engineering:
  input_dir: data/preprocessed
  output_dir: data/fe

model_training:
  input_dir: data/fe
  output_dir: models
  models:
    linear_regression:
      file: models/linear_regression.joblib
    random_forest:
      n_estimators: 100
      max_depth: 10
      file: models/random_forest.joblib
    xgboost:
      n_estimators: 200
      learning_rate: 0.1
      max_depth: 8
      file: models/xgboost.joblib

model_evaluation:
  input_dir: data/fe
  model_dir: models
  metrics_file: reports/metrics.json
