# params.yaml

base:
  random_state: 42

data_ingestion:
  input_path: "data/indian_restaurant_waste_dataset.csv"
  output_dir: "data/processed"
  test_size: 0.2

data_preprocessing:
  input_dir: "data/processed"
  output_dir: "data/processed"

feature_engineering:
  input_dir: "data/processed"
  output_dir: "data/processed"

model_training:
  input_dir: "data/processed"
  output_dir: "models"
  random_state: 42
  models:
    linear_regression:
      file: "models/lr_model.joblib"
    random_forest:
      file: "models/rf_model.joblib"
      n_estimators: 200
      max_depth: 8
    xgboost:
      file: "models/xgb_model.joblib"
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 6

model_evaluation:
  input_dir: "data/processed"
  model_dir: "models"
  metrics_file: "metrics/metrics.json"
  comparison_plot: "metrics/model_comparison.png"
